title:            PhoneBoy's Security Theater
description:      Confessions of a C-List CyberSecurity Celebrity
disqus_shortname: phoneboysecurity
reading_time:     true
words_per_minute: 170
logo:             everyones-a-target.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              http://phoneboy.org

gems: [jekyll-paginate]

# Owner/author information
owner:
  name:           Dameon D. Welch-Abernathy
  avatar:         avatar.jpg
  bio:            "C-List #Cybersecurity Celebrity üé§Podcaster üì°#noagenda Producer ‚úàÔ∏è Frequents shiny metal tubes üòù Expresses personal opinions ‚òïÔ∏è Coffee achiever"
  email:          dwelch@phoneboy.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        phoneboy
  facebook:       phoneboy
  github:         
  stackexchange:  
  linkedin:       phoneboy
  instagram:      phoneboy
  flickr:         phoneboy
  tumblr:         phoneboy
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +DameonWelchAbernathyAKAPhoneBoy

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-3289973-5
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:      8B84AAC4207331AB0E1AE3EEBD5E27B7   

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: rouge
markdown:    kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: coderay

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
